org_name   = "Sahurtado"
team_name  = "devops"
region     = "us-east-1"
codebuild_compute_type = "BUILD_GENERAL1_MEDIUM"
codebuild_image        = "aws/codebuild/amazonlinux-x86_64-standard:5.0"
codebuild_type         = "LINUX_CONTAINER"
codecommit_branch      = "main"