
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Installing Terraform and HCLQ...
      - tf_version=$TERRAFORM_VERSION
      - curl -sSLo install.sh https://install.hclq.sh
      - sh install.sh
      - yum install -y yum-utils shadow-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version


  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - cd aws_lambda_functions/
      - echo Updating ENV_namespace in terraform.tfvars
      - cat terraform.tfvars | hclq set 'env_namespace' $ENV_NAMESPACE | hclq set 'ecr_repo_url' $REPO_URI | hclq set 'ecr_repo_arn' $REPO_ARN | tee terraform.tfvars
      - terraform init -input=false
      - terraform validate
      - terraform apply -auto-approve